
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/zirtoshka/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 24.0.0 - arm64
...
